apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: nfs-server

resources:
- nfs-pv-local.yaml
- nfs-pv.yaml
- nfs-service.yaml
- nfs-ganesha.yaml
