apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

commonLabels:
  app: matnn

resources:
- create-cluster-role-binding.yaml
- create-service-account.yaml
- create-service-prometheus-grafana.yaml
- matnn-api-ingress.yaml
- matnn-ingress.yaml
- matnn-configmap.yaml
- matnn-service.yaml
- matnn-deployment.yaml
- matnn-metallb.yaml
- clusterissuer.yaml
