apiVersion: v1
kind: ConfigMap
metadata:
  name: matnn-config
  #namespace: default
data:
  matnn-config: |
    [nfs-server]
    host = 10.233.3.234
    mountdir = /mnt
    claim_name = nfs-claim
    storage_volume = nfs
    [dockerhub]
    image = intamixx/musicnn_v3:latest
  ssl-privatekey: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDcmv1egWUXq/+7
    2TwJxkC/TIv9FUN/Dk3OQH8vbiN75m6JxEZ+pVXutku2K2Q/beBu1ngHAu1RZDb9
    bovl//oiB1yzeRIf8P5WJF1rdfewl26WaN45esojgMbBUuAAMDMxF0B2uQhD0Q6L
    nhfhjkEpL6KViJFf1keMQ+49rqvVLip/koYQ5iJO1GgrxN5i/rmnm4rzBa9Lm7iP
    hdh+O/UH1BMkytYIG46JZz3owUMOnIqHM69oxJbCABV3NyKf/bUuesx0dZpL1Wes
    /6WkKtvWrnXhr12lH9l8ZbIPjRnweYXF/MTtQjAGMZF2iIj3hURJA0rXG5ybasho
    geqeGQuLAgMBAAECggEAUCoGHjx5BuQatyFWntqrFpjzWdFLSLVi8qsfTJYCUPjI
    fEmVsFnWYztdQeJ8uEvuPXiz/yBCKsx26xsrvTWKqKjyN8msG21Qju8B/5XLnyE4
    L3IGJu8G22XlU8UQ3yCkyZcAduQAK9yhI30cgntWFGhZ9Wq+IQxVzZO11DZP/NPv
    1VRx+0YgIUOUGpueAMnYeTC81adC7WFbmRp3CmgRW+VPteIAu/PIIaN4d4Hp9oJK
    eMkAKF1GGKY+EUYf1QLXAlWmuwmHtXFVnARWocCV+ryAS0H4syjYZlQ5idW+th6l
    /1cbjQgQwTPzVPxn4FyoxVBbydYwfC4/PgtbhBqzmQKBgQD8sKVrzG9mTEccUuLe
    HL9VIGSiL8TLfH5iKUBpLaDwSn9vY58Wz7U10dSCaiHkcQ9iW8OcA0hQOhhSuIm/
    X31ETgvuEJRxpZb5CVQ8EcPBdaE4bxgBy8poxxkjDH9cgLzrQzTTlJpf2iKssyag
    tK0V3Vo7SjMAL1NrxrzNYwvhxwKBgQDffsDSa61Lb81yDIxMnPn4LCyqJzvaVPFy
    iWvn5MlffMtD0t4g9JuTyr5tl9C58xqp9WqVV/J47Oz87+34P+y+AK9wv5H4QVvt
    puffGzLqvpbE567Y0lG3BNw/voh7o9t5lc56ycxlZ6gfU8tfU0vVhbHBifwpNG7e
    g+w/R7vIHQKBgQD4kniX24p2cnC9fxfncRYSkoQMO7t2hOf6fiP7k0QvPMmxdKlq
    EjdrUxeelvLyOvnsQuLg1SXMremBbkEq/a9HgxMfRDYSudcS8kdns/4CkElhL3/J
    PITHn5utq7yZ7ZZqRDlyLUvTIM1dX/qOuk1OJep+SpZzBxsj+WN/E4D7vwKBgBbi
    zO3/Nryt0zTlkgxaWsKOC3jVEaz2286lwdX6OKC9j7b/Rd3MDo5gyYVBcY9JFKbo
    yaRHYD3/zPjNvOmZ6i0+trht9Y2da8N3PvE6wMkHATtimiX7y4BZUBB6+1Dl45ic
    vYsXVQXhSncCxqWZSv+vdBdkgNzbUKsaiTulpdYFAoGBAK9oaYS2E/fKQteKE/mm
    VJezBnQxvXyNEKWqxNcFtSNGxbMAmRcUsZ6vRpVQ/N1JX96otdBmD3P/tlrShzIx
    wNe5hfFy/my3jYbP4ZEo7AfRxGotJ75t2+Kg35uGopwl57Nnl7WAt+cudYTxx7YA
    xbDXRt50+dHiO3XTL2o1NR4Q
    -----END PRIVATE KEY-----
  ssl-certificate: |
    -----BEGIN CERTIFICATE-----
    MIIE4zCCA8ugAwIBAgISBOeC8BZtrwi0BPsUB4BfgWIOMA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMzEwMjgxNDIwNDZaFw0yNDAxMjYxNDIwNDVaMBYxFDASBgNVBAMT
    C2ludGFtaXh4LnVrMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3Jr9
    XoFlF6v/u9k8CcZAv0yL/RVDfw5NzkB/L24je+ZuicRGfqVV7rZLtitkP23gbtZ4
    BwLtUWQ2/W6L5f/6Igdcs3kSH/D+ViRda3X3sJdulmjeOXrKI4DGwVLgADAzMRdA
    drkIQ9EOi54X4Y5BKS+ilYiRX9ZHjEPuPa6r1S4qf5KGEOYiTtRoK8TeYv65p5uK
    8wWvS5u4j4XYfjv1B9QTJMrWCBuOiWc96MFDDpyKhzOvaMSWwgAVdzcin/21LnrM
    dHWaS9VnrP+lpCrb1q514a9dpR/ZfGWyD40Z8HmFxfzE7UIwBjGRdoiI94VESQNK
    1xucm2rIaIHqnhkLiwIDAQABo4ICDTCCAgkwDgYDVR0PAQH/BAQDAgWgMB0GA1Ud
    JQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQW
    BBT9V5Wq3PWM7+NM3bpqAl9n3ufBuTAfBgNVHSMEGDAWgBQULrMXt1hWy65QCUDm
    H6+dixTCxjBVBggrBgEFBQcBAQRJMEcwIQYIKwYBBQUHMAGGFWh0dHA6Ly9yMy5v
    LmxlbmNyLm9yZzAiBggrBgEFBQcwAoYWaHR0cDovL3IzLmkubGVuY3Iub3JnLzAW
    BgNVHREEDzANggtpbnRhbWl4eC51azATBgNVHSAEDDAKMAgGBmeBDAECATCCAQQG
    CisGAQQB1nkCBAIEgfUEgfIA8AB2ANq2v2s/tbYin5vCu1xr6HCRcWy7UYSFNL2k
    PTBI1/urAAABi3bfluQAAAQDAEcwRQIgWYypByBgtc9WFuYFB30zba7PfKNCkiGY
    Tu5zHqUxM+gCIQDugPkBuphiHC5hGpoEMyij+0/8yn344VjAobuIgxqJpgB2AHb/
    iD8KtvuVUcJhzPWHujS0pM27KdxoQgqf5mdMWjp0AAABi3bflwIAAAQDAEcwRQIg
    W9/13hqGwxk7ymP3gHvOkXdbfpVNQd4pkq/+phLOM7ECIQDHkeJiqO3fdf8iz2mV
    aqsnUGRcP3eWB/75uS6FoaSxNjANBgkqhkiG9w0BAQsFAAOCAQEAGwhs75wPXCJp
    KE3y+k3TCDsy5ALdVmAKkwshsJIwskFjW6lAkLOLRU2Py/L8MAkj+qlJ56yq45uU
    M4G3CzwdQHfhXHyCl36q3AVMrd/0jpwHex36xnziudurnD4K+fxQtka3Eo6aYszp
    BEAOLCLE7vYAs7WRqRbWjzos+xHnO+N6t6iWkRnuPpVmJ/ZK9HboyViYibdImRMQ
    7Crr4pusBOrQms0o+MLkyT+Dx/GUGh9HjzunVnDy59NqM7RWo4w+sjKwM7/tg4Bq
    LQCgZHWmS3TQ9FuLSjNSx35rFrqI9FWno4Q8ZV79BwV+gMJxlXHIlt+T8rAfSv8C
    /27waxHZbw==
    -----END CERTIFICATE-----
