apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../matnn

patches:
  - path: replica_count.yaml
  - path: resource_limits.yaml
  - path: env.yaml

configMapGenerator:
  - name: matnn-config
    namespace: default
    behavior: merge
    files:
      - configs/config.json
